name: Deploy Airflow DAGs to MWAA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Sync DAGs to S3
        run: |
          aws s3 sync ./dags s3://airflow-mwaa-project/dags --delete

      - name: Sync requirements.txt
        run: |
          aws s3 cp ./requirements.txt s3://airflow-mwaa-project/requirements.txt
